# Generated by Django 3.2.7 on 2021-09-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_description', models.CharField(max_length=255)),
                ('passport_need', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('tour_days', models.IntegerField()),
                ('tour_type', models.IntegerField(choices=[(1, 'Active'), (2, 'Culture'), (3, 'Wine tour'), (4, 'Trekking'), (5, 'Incentive')])),
                ('tour_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours_app.country')),
            ],
        ),
    ]
