# Generated by Django 3.2.7 on 2021-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_foto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
