# Generated by Django 3.2.7 on 2021-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours_app', '0002_alter_tour_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='treking', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='type',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
